import type { Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    code: "rebalance",
    name: "LP Rebalancing",
    tagline: "Range management for concentrated liquidity, hands off.",
    userIntent: "I run V3 positions and I'm tired of re-centering ranges.",
    main: true,
    emoji: "⚖️",
    intents: ["lp_manage"],
  },
  {
    code: "grid",
    name: "Grid Trading",
    tagline: "Automated buy-low sell-high ladders for choppy markets.",
    userIntent: "Sideways market. I want the chop to pay me.",
    main: true,
    emoji: "🧮",
    intents: ["perps"],
  },
  {
    code: "yield",
    name: "Yield Routing",
    tagline: "Finds better APR, migrates positions, compounds on schedule.",
    userIntent: "There's a better vault somewhere. Go find it.",
    main: true,
    emoji: "🍯",
    intents: ["farm_vault", "stake_lst", "portfolio"],
  },
  {
    code: "hf",
    name: "Health Factor",
    tagline: "Watches lending positions, warns and assists before liquidation.",
    userIntent: "My Venus loan shouldn't wake me up at 4am.",
    main: true,
    emoji: "🫀",
    intents: ["lend_risk", "portfolio"],
  },
  {
    code: "swap_safe",
    name: "Swap Routing",
    tagline: "Path and slippage optimization for large or awkward swaps.",
    userIntent: "Big swap, weird pair. Don't let me get sandwiched.",
    main: false,
    emoji: "🔀",
    intents: ["swap"],
  },
  {
    code: "meme_radar",
    name: "Meme Radar",
    tagline: "Launch and momentum monitoring across BSC meme venues.",
    userIntent: "I refresh four.meme too much. Automate my eyes.",
    main: false,
    emoji: "📡",
    intents: ["meme_token", "wallet_track"],
  },
  {
    code: "smart_money",
    name: "Smart Money",
    tagline: "Wallet intelligence and copy-trade assistance.",
    userIntent: "Show me what wallets that win are doing right now.",
    main: false,
    emoji: "🧠",
    intents: ["wallet_track", "meme_token"],
  },
  {
    code: "bridge_route",
    name: "Bridge Routing",
    tagline: "Cross-chain routes compared by cost, speed and trust.",
    userIntent: "Move assets to BSC without overpaying the toll.",
    main: false,
    emoji: "🌉",
    intents: ["bridge"],
  },
  {
    code: "perps_risk",
    name: "Perps Risk",
    tagline: "Margin and liquidation-distance monitoring for perp positions.",
    userIntent: "Tell me before the exchange tells me.",
    main: false,
    emoji: "🌡️",
    intents: ["perps"],
  },
  {
    code: "portfolio",
    name: "Portfolio Check",
    tagline: "Full-position review that ends with a next step, not a chart.",
    userIntent: "I see the overview. Now what should I actually do?",
    main: false,
    emoji: "🧾",
    intents: ["portfolio"],
  },
  {
    code: "lst",
    name: "Liquid Staking",
    tagline: "BNB staking and LST re-use, optimized and monitored.",
    userIntent: "Stake BNB, then make the receipt token work too.",
    main: false,
    emoji: "💧",
    intents: ["stake_lst"],
  },
];

export const byCode = (code: string) => CATEGORIES.find((c) => c.code === code);
export const MAIN_CATEGORIES = CATEGORIES.filter((c) => c.main);
